---
.easy_ci:lint:go:
  image: golangci/golangci-lint:latest-alpine
  stage: lint
  extends: .easy_ci:cache:go
  script:
    - go mod download
    - golangci-lint version
    - golangci-lint run --enable-all --timeout 10m
  allow_failure: true

.easy-ci:lint:dockerfile:
  variables:
    DOCKERFILE: "Dockerfile"
  image: hadolint/hadolint:latest-alpine
  only:
    refs:
      - tags
      - branches
  script: hadolint $DOCKERFILE
  stage: lint
  allow_failure: true
